#!/usr/bin/env bash

print_style () {
    if [ "$2" == "info" ] ; then
        COLOR="96m"
    elif [ "$2" == "success" ] ; then
        COLOR="92m"
    elif [ "$2" == "warning" ] ; then
        COLOR="93m"
    elif [ "$2" == "danger" ] ; then
        COLOR="91m"
    else #default color
        COLOR="0m"
    fi

    STARTCOLOR="\e[$COLOR"
    ENDCOLOR="\e[0m"

    printf "$STARTCOLOR%b$ENDCOLOR" "$1"
}

display_options () {
    printf "Available options:\n";
    print_style "   go" "info"; printf "\t\t Enter workspace with laradock user\n"
    print_style "   go cf" "info"; printf "\t Enter workspace with laradock user and moved to sod-shared\n"
}

cws="/var/www"
dir=${PWD##*/}
ctn="${dir//-}_workspace_1"
dcm="docker exec -it -u laradock"

case $1 in
    go)
        case $2 in
            cf)
                cws="${cws}/cf"
                ;;
        esac

        cc="${dcm} -w ${cws} ${ctn} bash"
        print_style "Run: ${cc}\n" "info"
        ${cc}
        ;;
    *)
        display_options
        ;;
esac
